name: Build and Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          version: latest
          activate-environment: true
          enable-cache: true
          cache-suffix: "uv-cache"

      - name: Install dependencies with uv
        run: |
          uv pip install build pyinstaller
          uv pip install -r requirements.txt

      - name: Build wheel
        run: |
          uv run python -m build --wheel

      - name: Build binary
        run: |
          uv run pyinstaller .spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ runner.os }}
          path: |
            dist/*.whl
            dist/bili-identity*
