name: Build and Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install build pyinstaller
          uv pip install -r requirements.txt

      - name: Build wheel
        run: |
          uv python -m build --wheel

      - name: Build binary
        run: |
          uv pyinstaller --onefile bili_identity/main.py --name bili_identity --paths .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.2.1
        with:
          name: build-artifacts-${{ runner.os }}
          path: |
            dist/*.whl
            dist/bili_identity*
