name: Build and Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pyinstaller
          pip install -r requirements.txt

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Build Binary
        run: |
          pyinstaller --onefile bili_identity/main.py --name bili_identity --paths .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            dist/*.whl
            dist/bili_identity*
